import type { Metadata } from "next";
import Link from 'next/link';
import { Inter } from "next/font/google";
import {Open_Sans} from 'next/font/google';
import {Nanum_Gothic} from 'next/font/google';
import "./globals.css";
import styles from "./layout.module.css"

const inter = Inter({ subsets: ["latin"] });
const sans = Open_Sans({subsets: ["latin"]});
const gothic = Nanum_Gothic({
    weight: '700',
    subsets: ['latin'],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={sans.className}>
        <body>
        <header className={styles.header}>
            <h1 className={gothic.className}>Demo Note</h1>
            <nav className={styles.nav}>
                <Link href='/products'>Products</Link>
                <Link href='/about'>About</Link>
                <Link href='/contact'>Contact</Link>
            </nav>
        </header>
        {children}
        </body>
        </html>
    );
}
